modLoader="javafml"
loaderVersion="[35,)"
license="Creative Commons"

[[mods]]
modId="betterclay"
version="1.3.0"
displayName="Better Clay"
credits="Thanks to Avalon Team and my Twitter Followers." 
authors="Avalon Team."
description='''
BetterClay is a mod to complement the Clay elements in minecraft, are you bored with only one type of brick made of clay? 
This mod is for you. Experiment with the new Clay, Stoneware, Adobe, Earthware, Kaolin, Fireclay and Bentomite Bricks for enchancing your 
buildings.
'''